blank_issues_enabled: false
contact_links:
  - name: 🤔 Long question or idea
    url: https://github.com/pedroslopez/whatsapp-web.js/discussions
    about: Ask long-form questions and discuss ideas.
  - name: Official WWebJS Discord Server
    url: https://discord.gg/H7DqQs4
    about: Please ask and answer questions here.
